package com.imooc.seckill.entity;

import java.math.BigDecimal;

public class Good {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_tbl.id
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_tbl.title
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_tbl.price
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_tbl.description
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_tbl.sales
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_tbl.image_url
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_tbl.id
     *
     * @return the value of good_tbl.id
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_tbl.id
     *
     * @param id the value for good_tbl.id
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_tbl.title
     *
     * @return the value of good_tbl.title
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_tbl.title
     *
     * @param title the value for good_tbl.title
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_tbl.price
     *
     * @return the value of good_tbl.price
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_tbl.price
     *
     * @param price the value for good_tbl.price
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_tbl.description
     *
     * @return the value of good_tbl.description
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_tbl.description
     *
     * @param description the value for good_tbl.description
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_tbl.sales
     *
     * @return the value of good_tbl.sales
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_tbl.sales
     *
     * @param sales the value for good_tbl.sales
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_tbl.image_url
     *
     * @return the value of good_tbl.image_url
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_tbl.image_url
     *
     * @param imageUrl the value for good_tbl.image_url
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}