package com.imooc.seckill.entity;

public class Sequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info_tbl.name
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info_tbl.current_val
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    private Integer currentVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info_tbl.step
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info_tbl.name
     *
     * @return the value of sequence_info_tbl.name
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info_tbl.name
     *
     * @param name the value for sequence_info_tbl.name
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info_tbl.current_val
     *
     * @return the value of sequence_info_tbl.current_val
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    public Integer getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info_tbl.current_val
     *
     * @param currentVal the value for sequence_info_tbl.current_val
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    public void setCurrentVal(Integer currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info_tbl.step
     *
     * @return the value of sequence_info_tbl.step
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info_tbl.step
     *
     * @param step the value for sequence_info_tbl.step
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}