package com.imooc.seckill.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.id
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.name
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.gender
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.age
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.phone
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.registration_mode
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private String registrationMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_tbl.third_party_user_id
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    private String thirdPartyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.id
     *
     * @return the value of user_info_tbl.id
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.id
     *
     * @param id the value for user_info_tbl.id
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.name
     *
     * @return the value of user_info_tbl.name
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.name
     *
     * @param name the value for user_info_tbl.name
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.gender
     *
     * @return the value of user_info_tbl.gender
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.gender
     *
     * @param gender the value for user_info_tbl.gender
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.age
     *
     * @return the value of user_info_tbl.age
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.age
     *
     * @param age the value for user_info_tbl.age
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.phone
     *
     * @return the value of user_info_tbl.phone
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.phone
     *
     * @param phone the value for user_info_tbl.phone
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.registration_mode
     *
     * @return the value of user_info_tbl.registration_mode
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public String getRegistrationMode() {
        return registrationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.registration_mode
     *
     * @param registrationMode the value for user_info_tbl.registration_mode
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setRegistrationMode(String registrationMode) {
        this.registrationMode = registrationMode == null ? null : registrationMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_tbl.third_party_user_id
     *
     * @return the value of user_info_tbl.third_party_user_id
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public String getThirdPartyUserId() {
        return thirdPartyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_tbl.third_party_user_id
     *
     * @param thirdPartyUserId the value for user_info_tbl.third_party_user_id
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    public void setThirdPartyUserId(String thirdPartyUserId) {
        this.thirdPartyUserId = thirdPartyUserId == null ? null : thirdPartyUserId.trim();
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gender=" + gender +
                ", age=" + age +
                ", phone='" + phone + '\'' +
                ", registrationMode='" + registrationMode + '\'' +
                ", thirdPartyUserId='" + thirdPartyUserId + '\'' +
                '}';
    }
}