package com.imooc.seckill.dao;

import com.imooc.seckill.entity.Event;

public interface EventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tbl
     *
     * @mbg.generated Tue Dec 01 10:47:07 PST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tbl
     *
     * @mbg.generated Tue Dec 01 10:47:07 PST 2020
     */
    int insert(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tbl
     *
     * @mbg.generated Tue Dec 01 10:47:07 PST 2020
     */
    int insertSelective(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tbl
     *
     * @mbg.generated Tue Dec 01 10:47:07 PST 2020
     */
    Event selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tbl
     *
     * @mbg.generated Tue Dec 01 10:47:07 PST 2020
     */
    int updateByPrimaryKeySelective(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_tbl
     *
     * @mbg.generated Tue Dec 01 10:47:07 PST 2020
     */
    int updateByPrimaryKey(Event record);

    Event selectByGoodId(Integer id);
}