package com.imooc.seckill.dao;

import com.imooc.seckill.entity.Good;

import java.util.List;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    Good selectByPrimaryKey(Integer id);

    List<Good> listAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int updateByPrimaryKey(Good record);
}