package com.imooc.seckill.dao;

import com.imooc.seckill.entity.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Sat Oct 10 21:08:08 PDT 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Sat Oct 10 21:08:08 PDT 2020
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Sat Oct 10 21:08:08 PDT 2020
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Sat Oct 10 21:08:08 PDT 2020
     */
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Sat Oct 10 21:08:08 PDT 2020
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_tbl
     *
     * @mbg.generated Sat Oct 10 21:08:08 PDT 2020
     */
    int updateByPrimaryKey(Order record);
}