package com.imooc.seckill.dao;

import com.imooc.seckill.entity.Sequence;

public interface SequenceMapper {
    Sequence getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info_tbl
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info_tbl
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info_tbl
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info_tbl
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    Sequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info_tbl
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info_tbl
     *
     * @mbg.generated Wed Oct 14 21:38:04 PDT 2020
     */
    int updateByPrimaryKey(Sequence record);
}