package com.imooc.seckill.dao;

import com.imooc.seckill.entity.Stock;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int insert(Stock record);

    int reduceStock(int id, int amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    Stock selectByPrimaryKey(Integer id);

    Stock selectByGoodId(Integer goodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Sun Sep 27 16:12:26 PDT 2020
     */
    int updateByPrimaryKey(Stock record);
}