package com.imooc.seckill.dao;

import com.imooc.seckill.entity.TransactionHistory;

public interface TransactionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_tbl
     *
     * @mbg.generated Sun Dec 27 10:15:03 PST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_tbl
     *
     * @mbg.generated Sun Dec 27 10:15:03 PST 2020
     */
    int insert(TransactionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_tbl
     *
     * @mbg.generated Sun Dec 27 10:15:03 PST 2020
     */
    int insertSelective(TransactionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_tbl
     *
     * @mbg.generated Sun Dec 27 10:15:03 PST 2020
     */
    TransactionHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_tbl
     *
     * @mbg.generated Sun Dec 27 10:15:03 PST 2020
     */
    int updateByPrimaryKeySelective(TransactionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_tbl
     *
     * @mbg.generated Sun Dec 27 10:15:03 PST 2020
     */
    int updateByPrimaryKey(TransactionHistory record);
}