package com.imooc.seckill.dao;

import com.imooc.seckill.entity.UserAccount;

public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_tbl
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_tbl
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_tbl
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_tbl
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    UserAccount selectByPrimaryKey(Integer id);

    UserAccount selectByUserId(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_tbl
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_tbl
     *
     * @mbg.generated Sat Sep 12 10:27:11 PDT 2020
     */
    int updateByPrimaryKey(UserAccount record);
}